##
## Check GETTING_STARTED.markdown for additional properties and their default
## values.
##

liferay.workspace.bundle.dist.include.metadata=true
liferay.workspace.modules.dir=modules
liferay.workspace.themes.dir=themes
liferay.workspace.wars.dir=modules
microsoft.translator.subscription.key=

# Optional
#
# Either this property or liferay.workspace.docker.image.liferay is required
#
# Sets the Liferay product version. Will also set a Liferay Docker image version.
# See https://releases.liferay.com/releases.json for more information.
liferay.workspace.product=

# Optional
#
# Either this property or liferay.workspace.product is required
#
# Overrides the Liferay Docker image version defined in liferay.workspace.product
# Declare if you need a more specific version than the one provided through the
# product key above.
#
# You can also use this to reference a nightly build like liferay/dxp:7.4.13.nightly
liferay.workspace.docker.image.liferay=liferay/dxp:2025.q1.17-lts

# Optional
#
# Lists additional compose files to include
# You should not need to change this, it's mostly for debugging and testing.
lr.docker.environment.compose.files=

# Required
#
# Enable each service or "service" that you would like to include in your
# environment. If the value is "true" or "1", the service is enabled. Any other
# value (or a blank value) is ignored and disables the service.
lr.docker.environment.service.enabled[db2]=false
lr.docker.environment.service.enabled[elasticsearch]=false
lr.docker.environment.service.enabled[liferay]=true
lr.docker.environment.service.enabled[mariadb]=false
lr.docker.environment.service.enabled[mysql]=false
lr.docker.environment.service.enabled[postgres]=false
lr.docker.environment.service.enabled[webserver_http]=false
lr.docker.environment.service.enabled[webserver_https]=false

# Optional
#
# Set to "false" or "0" if you want to persist volume data between restarts
lr.docker.environment.clear.volume.data=false

# Optional
#
# Relative or absolute path to a directory containing data for the containers.
# These directories created from running docker-compose instances using:
#
# ./gradlew exportContainerData
lr.docker.environment.data.directory=data

# Required if using a database
#
# The database name to use. Only needed if a database dump uses a different
# database name.
lr.docker.environment.database.name=lportal

# Optional
#
# Set to "true" or "1" if you want to enable database partitioning (MySQL or PostgreSQL only)
lr.docker.environment.database.partitioning.enabled=false

# Optional
#
# Comma-separated list of URLs pointing to hotfixes. These will be automatically
# downloaded and copied to the Liferay container before startup.
lr.docker.environment.hotfix.urls=https://releases-cdn.liferay.com/dxp/hotfix/2025.q1.14-lts/liferay-dxp-2025.q1.14-lts-hotfix-192.zip

# Optional
#
# The namespace to use for the docker-compose instance. If not set, defaults to
# the name of the Gradle root project, which is the current folder's name if not
# set in settings.gradle. In general, you should not need to change this.
#lr.docker.environment.namespace=LRWSDE

# The number of cluster nodes to start up in addition to the main Liferay
# instance. Setting this to 0 means there is no clustering.
lr.docker.environment.cluster.nodes=0

# Optional
#
# The comma-delimited list of hostnames (domains) used to access Liferay when using a webserver.
lr.docker.environment.web.server.hostnames=localhost

# Optional
#
# Set to 'true' to enable Glowroot.
lr.docker.environment.glowroot.enabled=false

# Optional
#
# Set to 'true' or '1' to enable the YourKit integration.
lr.docker.environment.yourkit.enabled=false

# Optional
#
# The download URL of the YourKit agent.
lr.docker.environment.yourkit.url=https://www.yourkit.com/download/docker/YourKit-JavaProfiler-2025.3-docker.zip
